---
- hosts: jenkins
  become: yes
  become_user: root
  tasks:
    - name: ensure jenkins apt key is installed
      apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key

    - name: ensure the sources list file is present
      template: src=sources.j2.list dest=/etc/apt/sources.list

    - name: ensure apt package cache is up to date
      apt: update_cache=yes

    - name: ensure jenkins is installed
      apt: name=jenkins state=present

    - name: ensure that golang is installed
      apt: name=golang state=present

    # We use Ansible for deploying into production.
    - name: ensure that ansible is installed
      apt: name=ansible state=present
      register: jenkins_installed

    - name: get jenkins password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      when: jenkins_installed.changed

    - debug: var=jenkins_password.stdout
